export const SET_TRIP_BY = 'SET_TRIP_BY'
export const SET_TRIP_TYPE = 'SET_TRIP_TYPE'

export const SET_TRIP_SOURCE = 'SET_TRIP_SOURCE'
export const SET_TRIP_DESTINATION = 'SET_TRIP_DESTINATION'

export const SET_TRIP_STARTDATETIME = 'SET_TRIP_STARTDATETIME'
export const SET_TRIP_RETURNDATETIME = 'SET_TRIP_RETURNDATETIME'